difi/urls.py
from django.urls import path

from . import views

app_name = 'difi'

urlpatterns = [
    path('', views.index, name='index'),
    path('stock', views.select_stock_list, name='select_stock_list'),
    path('stock-value', views.select_stock_value_list, name='select_stock_value_list'),
    path('addstock', views.insert_stock, name='insert_stock'),
    path('deletestock',views.delete_stock, name='delete_stock'),
    path('updatestock',views.update_stock, name='update_stock'),
    path('calcstock',views.calc_stock, name='calc_stock'),
    path('login', views.login, name='login'),
    path('idcheck', views.id_check, name='id_check'),
    path('signup', views.signup, name='signup'),
    path('selectuser', views.select_user, name='select_user'),
    path('checkuser', views.check_user, name='check_user')

]

difi/models.py
from django.db import models

# Create your models here.
class stock(models.Model):
    stock_ticker = models.CharField(max_length=6, primary_key=True)
    stock_name = models.CharField(max_length=50)
    
    # def __str__(self):
    #     return self.subject
    def print_object_details(self):
    # 모델의 메타데이터에서 모든 필드 정보를 가져옵니다.
        fields = self._meta.get_fields()

        # 각 필드의 칼럼명과 값을 출력합니다.
        for field in fields:
            column_name = field.column
            value = getattr(self, field.name)
            print(f"{column_name}: {value}")

class user(models.Model):
    user_id = models.CharField(max_length=20, primary_key=True)
    user_name = models.CharField(max_length=20)
    user_password = models.CharField(max_length=1000)
    user_email = models.CharField(max_length=100)
    def print_object_details(self):
    # 모델의 메타데이터에서 모든 필드 정보를 가져옵니다.
        fields = self._meta.get_fields()

        # 각 필드의 칼럼명과 값을 출력합니다.
        for field in fields:
            column_name = field.column
            value = getattr(self, field.name)
            print(f"{column_name}: {value}")


class stock_value(models.Model):
    stock_ticker = models.ForeignKey(stock, on_delete=models.CASCADE)
    user_id = models.ForeignKey(user, on_delete=models.CASCADE)
    # stock_ticker = models.CharField(max_length=6)
    # user_id = models.CharField(max_length=20)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    start_date_close = models.IntegerField(null=True)
    end_date_close = models.IntegerField(null=True)
    quantity = models.IntegerField(null=True)
    start_date_close_total = models.IntegerField(null=True)
    end_date_close_total = models.IntegerField(null=True)
    profit_loss = models.IntegerField(null=True)
    return_rate = models.DecimalField(null=True, max_digits=19, decimal_places=4)
    weight = models.DecimalField(null=True, max_digits=19, decimal_places=4)
   
    # 모델의 메타데이터에서 모든 필드 정보를 가져옵니다.
    def print_object_details(self):
    # 모델의 메타데이터에서 모든 필드 정보를 가져옵니다.
        fields = self._meta.get_fields()

        # 각 필드의 칼럼명과 값을 출력합니다.
        for field in fields:
            column_name = field.column
            value = getattr(self, field.name)
            print(f"{column_name}: {value}")

    class Meta:
        unique_together = (('stock_ticker', 'user_id'),)

class stock_timestamp(models.Model):
    date = models.DateField()
    close = models.IntegerField()
    change = models.DecimalField(max_digits=19, decimal_places=6)
    stock_ticker = models.CharField(max_length=6)
    user_id = models.ForeignKey(user, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = (('stock_ticker', 'user_id', 'date'),)
# class stock_value(models.Model):
#     ticker = models.TextField()
#     stock_name = models.TextField()
#     startDate = models.DateField(null=True)
#     endDate = models.DateField(null=True)
#     startDate_close = models.IntegerField(null=True)
#     endDate_close = models.IntegerField(null=True)
#     quantity = models.IntegerField(null=True)
#     start_value = models.IntegerField(null=True)
#     end_value = models.IntegerField(null=True)
#     ugl = models.IntegerField(null=True)
#     return_rate = models.DecimalField(null=True, max_digits=19, decimal_places=4)
#     weight = models.DecimalField(null=True, max_digits=19, decimal_places=4)

# class result(models.Model):
#     total_start_value = models.IntegerField()
#     total_start_value = models.IntegerField()
#     pf_err = models.DecimalField(max_digits=19, decimal_places=4)
#     pf_risk = models.DecimalField(max_digits=19, decimal_places=4)
#     total_ugl = models.IntegerField()
#     total_rr = models.DecimalField(max_digits=19, decimal_places=4)
    
    
    
    
    

difi/forms.py
from django import forms
# from difi.models import stock_value, stock_ts

# class StockValueForm(forms.ModelForm):
#     class Meta:
#         model = stock_value  # 사용할 모델
#         fields = ['startDate', 'endDate', 'stock_name', 'ticker']  # QuestionForm에서 사용할 Question 모델의 속성

# class StockTsForm(forms.ModelForm):
#     class Meta:
#         model = stock_ts  # 사용할 모델
#         fields = ['ticker']  # QuestionForm에서 사용할 Question 모델의 속성

difi/views.py
from django.shortcuts import render, redirect
from .models import stock, stock_value, stock_timestamp, user
# from .forms import StockValueForm, StockTsForm 
from django.db.models import Q
import FinanceDataReader as fdr
from django.http import HttpResponse
from django.http import JsonResponse
from django.core import serializers
import json
from django.views.decorators.csrf import csrf_exempt
# from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.db import transaction
from django.db.models import F
import numpy as np
from django.db.models import StdDev, Avg
import pandas as pd
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices
from django.contrib.auth.hashers import make_password, check_password
import jwt
from django.conf import settings
from datetime import datetime, timedelta
import bcrypt
from django.utils.crypto import get_random_string
from django.core.cache import cache

@csrf_exempt
def index(request):
    return HttpResponse("avc")

@csrf_exempt
def select_stock_list(request):
    if request.method == 'POST':
        request_body = json.loads(request.body)
        inq_content = request_body.get('inq_content')

        if inq_content is None:
            return HttpResponse(error_message(data="inq_content", code="001"), status=500)

        stock_list = stock.objects.filter(
            Q(stock_ticker__icontains=inq_content) | 
            Q(stock_name__icontains=inq_content)
        ).distinct()

        result = serializers.serialize('json',stock_list)

        return HttpResponse(result,content_type="application/json")
    else:
        return HttpResponse(error_message(code=100), status=500)

@transaction.atomic
@csrf_exempt
def insert_stock(request):
    if request.method=='POST':
        request_body = json.loads(request.body)
        stock_ticker_in = request_body.get('stock_ticker')
        start_date_in  = request_body.get('start_date')
        end_date_in  = request_body.get('end_date')
        user_id_in = request_body.get('user_id')

        if stock_ticker_in is None or stock_ticker_in == "":
            return HttpResponse(error_message(data="stock_ticker", code="001"), status=500)
        if start_date_in is None or start_date_in == "":
            return HttpResponse(error_message(data="start_date", code="001"), status=500)
        if end_date_in is None or end_date_in == "":
            return HttpResponse(error_message(data="end_date", code="001"), status=500)
        if user_id_in is None or user_id_in == "":
            return HttpResponse(error_message(data="user_id", code="001"), status=500)
        
        stock_ts = fdr.DataReader(stock_ticker_in,start_date_in,end_date_in).filter(['Close','Change'])

        if stock_ts is None or len(stock_ts) == 0:
            return HttpResponse(error_message(code="002", content="stock_ts is empty"), status=500)

        stock_ts = stock_ts.reset_index()
        
        for i in range(len(stock_ts)):
            stock_ts_tuple = stock_ts.iloc[i]
            stock_timestamp.objects.create(date=stock_ts_tuple['Date'], close=stock_ts_tuple['Close'], change=stock_ts_tuple['Change'], stock_ticker=stock_ticker_in, user_id_id=user_id_in)
        
        start_date_close = stock_ts.iloc[0, 1]
        end_date_close = stock_ts.iloc[-1, 1]
        
        stock_value.objects.create(stock_ticker_id=stock_ticker_in,
                                   user_id_id=user_id_in,
                                   start_date=start_date_in,
                                   end_date=end_date_in,
                                   start_date_close=start_date_close,
                                   end_date_close=end_date_close
                                   )
        
        stock_value_list = stock_value.objects.all()
        result = serializers.serialize('json', stock_value_list)
        
        return HttpResponse(result, content_type="application/json")
    
    else :
        
        return HttpResponse(error_message(code=100), status=500)

@csrf_exempt
def select_stock_value_list(request):
    if request.method == 'POST':
        request_body = json.loads(request.body)
        user_id_in = request_body.get('user_id')

        if user_id_in is None or user_id_in == "":
            return HttpResponse(error_message(data="user_id", code="001"), status=500)

        stock_value_list = stock_value.objects.select_related('stock_ticker').filter(user_id=user_id_in)
        
        result = json.dumps(list(stock_value_list.values('stock_ticker','start_date','end_date','start_date_close','end_date_close','quantity','start_date_close_total','end_date_close_total','profit_loss','return_rate','weight','stock_ticker__stock_name')), default=str)

        return HttpResponse(result, content_type="application/json")
    else:
        return HttpResponse(error_message(code=100), status=500)

@transaction.atomic
@csrf_exempt
def delete_stock(request):
    if request.method == 'POST':
        request_body = json.loads(request.body)
        stock_ticker_in = request_body.get('stock_ticker')
        user_id_in = request_body.get('user_id')

        if stock_ticker_in is None or stock_ticker_in == "":
            return HttpResponse(error_message(data="stock_ticker", code="001"), status=500)
        if user_id_in is None or user_id_in == "":
            return HttpResponse(error_message(data="user_id", code="001"), status=500)

        stock_timestamp_out = stock_timestamp.objects.filter(stock_ticker=stock_ticker_in, user_id=user_id_in)
        
        if not stock_timestamp_out.exists():
            return HttpResponse(error_message(code="003", content="stock_timestamp is no data"), status=500)
        
        stock_timestamp_out.delete()

        stock_value_out = stock_value.objects.get(stock_ticker=stock_ticker_in, user_id=user_id_in)
        
        if not stock_value_out.exists():
            return HttpResponse(error_message(code="003", content="stock_value is no data"), status=500)

        stock_value_out.delete()

        return HttpResponse('success', content_type="application/json")
    else:
        return HttpResponse(error_message(code=100), status=500)

@transaction.atomic
@csrf_exempt
def update_stock(request):
    if request.method == 'POST':
        request_body = json.loads(request.body)
        stock_value_list = request_body.get('stock_value_list')
        user_id_in = request_body.get('user_id')

        if stock_value_list is None or len(stock_value_list) < 1:
            return HttpResponse(error_message(data="stock_value_list", code="001"), status=500)
        if user_id_in is None or user_id_in == "":
            return HttpResponse(error_message(data="user_id", code="001"), status=500)

        for i in stock_value_list:
            if stock_value.objects.filter(stock_ticker=i['stock_ticker'], user_id=user_id_in).exists():
                stock_value.objects.filter(stock_ticker=i['stock_ticker'], user_id=user_id_in).update(quantity=int(i["quantity"]))
                stock_value.objects.filter(stock_ticker=i['stock_ticker'], user_id=user_id_in).update(start_date_close_total=i["start_date_close_total"])
                stock_value.objects.filter(stock_ticker=i['stock_ticker'], user_id=user_id_in).update(end_date_close_total=i["end_date_close_total"])
                stock_value.objects.filter(stock_ticker=i['stock_ticker'], user_id=user_id_in).update(profit_loss=i["profit_loss"])
                stock_value.objects.filter(stock_ticker=i['stock_ticker'], user_id=user_id_in).update(return_rate=i["return_rate"])

            else:
                return HttpResponse(error_message(code="003", content="stock_value is no data"), status=500)
            

        return HttpResponse('success', content_type="application/json")
    else:
        return HttpResponse(error_message(code=100), status=500)
    
@transaction.atomic
@csrf_exempt
def calc_stock(request):
    if request.method == 'POST':
        request_body = json.loads(request.body)
        stock_value_list = request_body.get('stock_value_list')
        user_id_in = request_body.get('user_id')

        if stock_value_list is None or len(stock_value_list) < 1:
            return HttpResponse(error_message(data="stock_value_list", code="001"), status=500)
        if user_id_in is None or user_id_in == "":
            return HttpResponse(error_message(data="user_id", code="001"), status=500)

        kospi_index = fdr.DataReader("KS11",stock_value_list[0].get("start_date"),stock_value_list[0].get("end_date")).filter(['Change'])

        if kospi_index is None or len(kospi_index) < 1:
            return HttpResponse(error_message(code="003", content="kospi_index is no data"), status=500)

        kospi_std = np.std(kospi_index["Change"])
        kospi_avg = np.average(kospi_index["Change"])
        kospi_coef = (kospi_std / kospi_avg)

        grand_start_total= 0
        grand_end_total = 0

        stock_std_sum = 0
        stock_coef_sum = 0

        stock_ts_obj = {}

        stock_df_all = pd.DataFrame([])

        weights = np.array([])

        for i in stock_value_list:

            grand_start_total += i["start_date_close_total"]
            grand_end_total += i["end_date_close_total"]

            stock_ts = stock_timestamp.objects.filter(stock_ticker=i["stock_ticker"], user_id=user_id_in)

            if not stock_ts.exists():
                return HttpResponse(error_message(code="003", content="stock_ts is no data"), status=500)

            stock_ts_list = []
            
            stock_name = stock.objects.get(stock_ticker=i["stock_ticker"]).stock_name
            
            if stock_name is None or stock_name == "":
                return HttpResponse(error_message(data="stock_name", code="001"), status=500)

templates/difi/search.html
<div class="col-6">
    <div class="input-group">
        <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
        </div>
    </div>
</div>

templates/difi/upper.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text"> 투자기간 :
                <input type="date"> ~ <input type="date">
            </div>
            <br>
            
            <div class="card-text"> 종목 :  
                <input type="search" placeholder="종목코드/종목명" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            </div>
            
        </div>
        <form>
            <form method="post" action="{% url 'difi:index' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">추가</button>
            </form>
            {% comment %} <a href="{% url 'difi:index' %}" class="btn btn-primary">추가</a> {% endcomment %}
          </form>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">종목검색</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="search" id="search_kw" class="form_control"  value="{{ kw|default_if_none:'' }}" placeholder="종목명 or 종목코드 입력" size="25"> 

                <button class="btn btn-outline-secondary" id="btn_search" type="button">검색</button>
            </div>
            <div class="modal-footer">
            
            <button type="button" class="btn btn-primary">Ok</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
</div>

<div class="container my-3">
    <div class="card my-3">
        <div class="card-body">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">종목명</th>
                    <th scope="col">종목코드</th>
                    <th scope="col">매입가</th>
                    <th scope="col">현재가</th>
                    <th scope="col">수량</th>
                    <th scope="col">매입금액</th>
                    <th scope="col">평가금액</th>
                    <th scope="col">평가손익</th>
                    <th scope="col">수익률</th>
                    <th scope="col">투자비율</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                  </tr>
                </tbody>
              </table>
        </div>
        <a href="{% url 'difi:index' %}" class="btn btn-primary">계산</a>
    </div>
</div>

<div class="container my-3">
    <div class="card my-3">
        <div class="card-body">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">총 투자금액</th>
                    <th scope="col">총 평가금액</th>
                    <th scope="col">총 평가손익</th>
                    <th scope="col">총 수익률</th>
                    <th scope="col">PF 기대수익률</th>
                    <th scope="col">PF 위험</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td></td>
                    <td></td>
                    <td></td>
                  </tr>
                </tbody>
              </table>
        </div>
        <a href="{% url 'difi:index' %}" class="btn btn-primary">계산</a>
    </div>
</div>
<form id="searchForm" method="get" action="{% url 'difi:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script src='https://code.jquery.com/jquery-3.4.1.js'></script>
<script type='text/javascript'>

    $('#btn_search').on('click', function(){
        console.log("검색");
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('searchForm').submit();
        ;
      });
</script>
{% endblock %}